name: getx_best_places
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  path: ^1.8.0
  sqflite: ^2.0.2+1
  location: ^4.3.0
  google_maps_flutter: ^2.1.4

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

